controller:
  image:
    repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller-arm64
    tag: 0.24.1
  extraArgs:
    tcp-services-configmap: default/nginx-tcp-configmap
    udp-services-configmap: default/nginx-udp-configmap

defaultBackend:
  image:
    repository: k8s.gcr.io/defaultbackend-arm64
    tag: 1.5
