---
apiVersion: v1
kind: Service
metadata:
  name: pihole-admin
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
  - port: 80
    targetPort: 80
    name: pihole-admin
  externalTrafficPolicy: Local
