---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: 53
    nodePort: 30053
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    nodePort: 30053
    protocol: UDP
    name: dns-udp
  externalTrafficPolicy: Local
